title: Henry Cox
description: > # this means to ignore newlines until "baseurl:"
  I am PhD student at the University of Manchester working on Biological Physics. 
  This site contains blog posts about my projects in research, data science, machine learning and more...
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://henrycox.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Henry Cox # add your name
author-img: Henry-Cox.jpg # add your photo
about-author: I am PhD student at the University of Manchester working on Biological Physics. 
    
    # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: h-cox # add your Github handle
social-linkedin: henryfcox # add your Linkedin handle
social-email: henryfcox@live.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-117678824-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
